name: Polaris [SAST, SCA]

on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * SUN'

jobs:      
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: install npm
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          
      - name: install dependency
        run: |
          npm install --no-audit --no-fund --silent
          mkdir ./sarifs
          mkdir ./processed-sarifs
          
      - name: Polaris Scan
        uses: blackduck-inc/black-duck-security-scan@v2.0.0
        ### Configure DETECT environment variables
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          
        with:
          ### SCANNING: Required fields
          blackducksca_url: ${{ vars.BLACKDUCK_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
         
          ### SCANNING: Optional fields
          blackducksca_scan_failure_severities: 'BLOCKER,CRITICAL'
          
          ### FIX PULL REQUEST CREATION: Uncomment below to enable
          blackducksca_fixpr_enabled: true
          blackducksca_prcomment_enabled: true 
          githubToken: ${{ secrets.GITHUB_TOKEN }}

          ### SARIF report generation and upload to GitHub Adavanced Security: Uncomment below to enable
          blackducksca_reports_sarif_create: true # Create Black Duck SCA SARIF report and upload it as artifact
          blackducksca_upload_sarif_report: true  # Upload Black Duck SCA SARIF report in GitHub Advanced Security tab
