on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 48 1 * * *
  
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      - run: |
          semgrep ci --sarif-output=results.sarif
      
      - name: Add SCW Training
        uses: SecureCodeWarrior/github-action-add-sarif-contextual-training@v1
        if: always()
        with:
          inputSarifFile: ./results.sarif
          outputSarifFile: ./processed-sarifs
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: DBG only
        if: always()
        run: |
          ls -lrt ./sarifs
          ls -lrt ./processed-sarifs
          
      - name: Upload SARIF file
        uses: actions/upload-artifact@v4
        if: always()
        with:
          path: ./processed-sarifs
